### ISSUE TITLE
Get Iodide template addition into production.

### ISSUE THREAD

**Issue by gmierz** [mozilla/mach-perftest-notebook-dev#22]
This issue is for tracking the work required to give the production Iodide the ability to accept template notebooks from a POST request.

**Comment by gmierz** [comment]
Tracking this issue: https://github.com/iodide-project/iodide/issues/2681

**Comment by Octocat1337** [comment]
https://github.com/iodide-project/iodide/pull/2690 
I'll finish this so wlach can do a merge
I need to write my own test file for my pull request

**Comment by wlach** [comment]
This was extremely non-trivial to implement the full POST request functionality, but see iodide-project/iodide#2849. Thanks @Ralts1337 for writing some tests and helping things along!
