### ISSUE TITLE
Handle large data sets in Iodide

### ISSUE THREAD

**Issue by gmierz** [mozilla/mach-perftest-notebook-dev#23]
This issue is to determine how we could use large data sets in Iodide. At the moment, we have issues in the browsers when the data sets get too large.

Could there be a better way of serving the data to the browser from our local Flask server?

**Comment by Octocat1337** [comment]
180MB data works fine now. Previous browser crash was caused by iodide not supporting scipy.
Currently, 180MB data takes about 30 secs for iodide/browser to process.
Iodide page will freeze though during that 30 secs.
I'm not sure about bigger data file size

**Comment by gmierz** [comment]
Ah ok, good to know. Maybe we should mention this in the notebook (a simple comment would suffice).
